version: '3.2'
services:
  jenkins:
    image: jenkins/jenkins
    volumes:
      - ./jenkins:/var/jenkins_home:rw
      - ./war:/mnt/:rw
    ports:
      - 8080:8080
    container_name: jenkins
    deploy:
      resources:
        limits:
          cpus: '500m'
          memory: 50M
        reservations:
          cpus: '200m'
          memory: 20M
         
  
  tomcat:
    image: mzain/tomcat
    ports:
      - 7777:8080
    container_name: tomcat
    depends_on:
      - jenkins
    volumes:
      - ./war/:/usr/local/tomcat/webapps
    deploy:
      resources:
        limits:
          cpus: '500m'
          memory: 50M
        reservations:
          cpus: '200m'
          memory: 20M

